#ifndef RAW_STATS_HPP
#define RAW_STATS_HPP

namespace Riot
{
	struct RawStats
	{
		int assists;
		int barracksKilled;
		int championsKilled;
		int combatPlayerScore;
		int consumablesPurchased;
		int damageDealtPlayer;
		int doubleKills;
		int firstBlood;
		int gold;
		int goldEarned;
		int goldSpent;
		int item0;
		int item1;
		int item2;
		int item3;
		int item4;
		int item5;
		int item6;
		int itemsPurchased;
		int killingSprees;
		int largestCriticalStrike;
		int largestKillingSpree;
		int largestMultiKill;
		int legendaryItemsCreated;
		int level;
		int magicDamageDealtPlayer;
		int magicDamageDealtToChampions;
		int magicDamageTaken;
		int minionsDenied;
		int minionsKilled;
		int neutralMinionsKilled;
		int neutralMinionsKilledEnemyJungle;
		int neutralMinionsKilledYourJungle;
		bool nexusKilled;
		int nodeCapture;
		int nodeCaptureAssist;
		int nodeNeutralize;
		int nodeNeutralizeAssist;
		int numDeaths;
		int numItemsBought;
		int objectivePlayerScore;
		int pentaKills;
		int physicalDamageDealtPlayer;
		int physicalDamageDealtToChampions;
		int physicalDamageTaken;
		int quadraKills;
		int sightWardsBought;
		int spell1Cast;
		int spell2Cast;
		int spell3Cast;
		int spell4Cast;
		int summonSpell1Cast;
		int summonSpell2Cast;
		int superMonsterKilled;
		int team;
		int teamObjective;
		int timePlayed;
		int totalDamageDealt;
		int totalDamageDealtToChampions;
		int totalDamageTaken;
		int totalHeal;
		int totalPlayerScore;
		int totalScoreRank;
		int totalTimeCrowdControlDealt;
		int totalUnitsHealed;
		int tripleKills;
		int trueDamageDealtPlayer;
		int trueDamageDealtToChampions;
		int trueDamageTaken;
		int turretsKilled;
		int unrealKills;
		int victoryPointTotal;
		int visionWardsBought;
		int wardKilled;
		int wardPlaced;
		bool win;
	};
}

#endif // RAW_STATS_HPP