#ifndef RAW_STATS_HPP
#define RAW_STATS_HPP

#include "DTOField.hpp"

namespace Riot
{
	struct RawStats
	{
		DTOField<int> assists;
		DTOField<int> barracksKilled;
		DTOField<int> championsKilled;
		DTOField<int> combatPlayerScore;
		DTOField<int> consumablesPurchased;
		DTOField<int> damageDealtPlayer;
		DTOField<int> doubleKills;
		DTOField<int> firstBlood;
		DTOField<int> gold;
		DTOField<int> goldEarned;
		DTOField<int> goldSpent;
		DTOField<int> item0;
		DTOField<int> item1;
		DTOField<int> item2;
		DTOField<int> item3;
		DTOField<int> item4;
		DTOField<int> item5;
		DTOField<int> item6;
		DTOField<int> itemsPurchased;
		DTOField<int> killingSprees;
		DTOField<int> largestCriticalStrike;
		DTOField<int> largestKillingSpree;
		DTOField<int> largestMultiKill;
		DTOField<int> legendaryItemsCreated;
		DTOField<int> level;
		DTOField<int> magicDamageDealtPlayer;
		DTOField<int> magicDamageDealtToChampions;
		DTOField<int> magicDamageTaken;
		DTOField<int> minionsDenied;
		DTOField<int> minionsKilled;
		DTOField<int> neutralMinionsKilled;
		DTOField<int> neutralMinionsKilledEnemyJungle;
		DTOField<int> neutralMinionsKilledYourJungle;
		DTOField<bool> nexusKilled;
		DTOField<int> nodeCapture;
		DTOField<int> nodeCaptureAssist;
		DTOField<int> nodeNeutralize;
		DTOField<int> nodeNeutralizeAssist;
		DTOField<int> numDeaths;
		DTOField<int> numItemsBought;
		DTOField<int> objectivePlayerScore;
		DTOField<int> pentaKills;
		DTOField<int> physicalDamageDealtPlayer;
		DTOField<int> physicalDamageDealtToChampions;
		DTOField<int> physicalDamageTaken;
		DTOField<int> quadraKills;
		DTOField<int> sightWardsBought;
		DTOField<int> spell1Cast;
		DTOField<int> spell2Cast;
		DTOField<int> spell3Cast;
		DTOField<int> spell4Cast;
		DTOField<int> summonSpell1Cast;
		DTOField<int> summonSpell2Cast;
		DTOField<int> superMonsterKilled;
		DTOField<int> team;
		DTOField<int> teamObjective;
		DTOField<int> timePlayed;
		DTOField<int> totalDamageDealt;
		DTOField<int> totalDamageDealtToChampions;
		DTOField<int> totalDamageTaken;
		DTOField<int> totalHeal;
		DTOField<int> totalPlayerScore;
		DTOField<int> totalScoreRank;
		DTOField<int> totalTimeCrowdControlDealt;
		DTOField<int> totalUnitsHealed;
		DTOField<int> tripleKills;
		DTOField<int> trueDamageDealtPlayer;
		DTOField<int> trueDamageDealtToChampions;
		DTOField<int> trueDamageTaken;
		DTOField<int> turretsKilled;
		DTOField<int> unrealKills;
		DTOField<int> victoryPointTotal;
		DTOField<int> visionWardsBought;
		DTOField<int> wardKilled;
		DTOField<int> wardPlaced;
		DTOField<bool> win;
	};
}

#endif // RAW_STATS_HPP